version: '0.1'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    restart: always
  qdrant-connector:
    build: ./connector
    ports:
      - "8101:8101"
    restart: always
    depends_on: 
      - qdrant